title = "ads"
#baseURL = "https://gohugo-theme-ananke.pages.dev"
baseURL = "https://adsyl.github.io/ads.github.io/"
languageCode = "zh-cn"
theme = 'ananke'
publishDir = "docs"
resourceDir = "../resources"

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
"pagination.pagerSize" = 6           
googleAnalytics = ""
enableRobotsTXT = true

[languages]
[languages.zh]
title = "爱得生"
weight = 1
languageName = "简体中文"
contentDir = "content/zh"


[languages.en]
title = "adsmed"
weight = 2
languageName = "English"
contentDir = "content/en"

[sitemap]
changefreq = "weekly"
priority = 0.8
filename = "sitemap.xml"

[params]
text_color = ""
author = "ads"
dateFormat = "2006/01/02"
favicon = "images/favicon32.ico"           # 网站 Favicon 路径，例如 "/images/favicon.ico"
site_logo = "images/logo1.png"         # 网站 Logo 路径，例如 "/images/logo.png"
description = "爱得生，专业三代试管服务商"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3
read_more_copy = "Read more"  #该参数会影响所有页面的“阅读更多”链接的文字


[params.ananke.social] # 这是一个 TOML 表，不是数组
    # 配置要显示的社交网络列表
    [params.ananke.social.follow]
     new_window_icon = false
      networks = ["weixin","weibo","kuaishou","xhs","zhihu"]

[params.ananke.social.networks.weixin]    
#  username = "wechat" # 自定义名称，对应 wechat.svg
 profile = "https://twitter.com/GoHugoIO" # 替换为你的微信链接或二维码图片链接
 label = "微信" # 显示的文本标签
 icon = "weixin" 

[params.ananke.social.networks.zhihu]
slug = "zhihu"
label = "知乎"
profile = "https://www.zhihu.com/people/ziqo-xu"
 icon = "zhihu-ic" 

[params.ananke.social.networks.weibo]
slug = "weibo"
label = "微博"
#color = "#0077b5"
profile = "https://weibo.com/u/1703371307?lpage=profileRecom"
icon = "weibo" # font awesome brand icon name

[params.ananke.social.networks.xhs]    
#  username = "wechat" # 自定义名称，对应 wechat.svg
 profile = "https://twitter.com/GoHugoIO" # 替换为你的微信链接或二维码图片链接
 label = "小红书" # 显示的文本标签
 icon = "xhs-ic" 

[params.ananke.social.networks.kuaishou]    
#  username = "wechat" # 自定义名称，对应 wechat.svg
 profile = "https://twitter.com/GoHugoIO" # 替换为你的微信链接或二维码图片链接
 label = "快手" # 显示的文本标签
 icon = "kuaishou" 
